version: '3.1'

services:
  digital-signature:
    container_name: digital-signature
    image: digital-signature:latest
    restart: always
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - .env