export enum Topic {
    ATTEST_INVOICE = 'INVOICE.ATTEST',
    ATTEST_CREDIT_NOTE = 'CREDIT_NOTE.ATTEST',
    VERIFY_INVOICE = 'INVOICE.VERIFY',
    CREDIT_NOTE_CREATED = 'CREDIT_NOTE.CREATED',
    INVOICE_GENERATED =  'INVOICE.GENERATED',
    REPLY_TOPIC = 'REPLY-TOPIC',
}